In [114]:
import pandas as pd

In [115]:
df = pd.read_csv('./train.csv')
df.head()

Unnamed: 0  pelvic_incidence  pelvic_tilt  lumbar_lordosis_angle  \
0           0         39.056951    10.060991              25.015378   
1           1         68.832021    22.218482              50.092194   
2           2         49.712859     9.652075              28.317406   
3           3         40.250200    13.921907              25.124950   
4           4         53.432928    15.864336              37.165934   

   sacral_slope  pelvic_radius  degree_spondylolisthesis   class  
0     28.995960     114.405425                  4.564259  Hernia  
1     46.613539     105.985135                 -3.530317  Hernia  
2     40.060784     108.168725                  7.918501  Hernia  
3     26.328293     130.327871                  2.230652  Hernia  
4     37.568592     120.567523                  5.988551  Hernia

In [116]:
df['class'].value_counts()/df.shape[0]

Spondylolisthesis    0.483871
Normal               0.322581
Hernia               0.193548
Name: class, dtype: float64

In [117]:
df.columns

Index(['Unnamed: 0', 'pelvic_incidence', 'pelvic_tilt',
       'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius',
       'degree_spondylolisthesis', 'class'],
      dtype='object')

In [118]:
y=df['class']
x=df.drop(['class','Unnamed: 0'], axis=1)

In [119]:
x.head()

pelvic_incidence  pelvic_tilt  lumbar_lordosis_angle  sacral_slope  \
0         39.056951    10.060991              25.015378     28.995960   
1         68.832021    22.218482              50.092194     46.613539   
2         49.712859     9.652075              28.317406     40.060784   
3         40.250200    13.921907              25.124950     26.328293   
4         53.432928    15.864336              37.165934     37.568592   

   pelvic_radius  degree_spondylolisthesis  
0     114.405425                  4.564259  
1     105.985135                 -3.530317  
2     108.168725                  7.918501  
3     130.327871                  2.230652  
4     120.567523                  5.988551

In [120]:
x.describe()

pelvic_incidence  pelvic_tilt  lumbar_lordosis_angle  sacral_slope  \
count        217.000000   217.000000             217.000000    217.000000   
mean          60.458343    17.541355              52.660081     42.916988   
std           18.045677    10.786425              19.226267     13.631236   
min           26.147921    -6.554948              14.000000     13.516568   
25%           46.236399     9.976664              36.329137     33.366366   
50%           57.145851    16.417462              51.000000     42.447102   
75%           74.469082    22.432950              63.232302     51.766175   
max          129.834041    49.431864             125.742385    121.429566   

       pelvic_radius  degree_spondylolisthesis  
count     217.000000                217.000000  
mean      118.073520                 27.715448  
std        13.920744                 40.965137  
min        70.082575                -11.058179  
25%       110.660701                  1.517203  
50%       118.151531                 13.683047  
75%       126.398188                 49.159426  
max       163.071041                418.543082

In [121]:
from sklearn.preprocessing import StandardScaler

In [122]:
x = StandardScaler().fit_transform(x)
x

array([[-1.18869883, -0.69510135, -1.44118569, -1.02362078, -0.26410769,
        -0.5664504 ],
       [ 0.46509972,  0.43461494, -0.13387024,  0.27180937, -0.87037981,
        -0.76450397],
       [-0.59683705, -0.7330993 , -1.26904294, -0.21001821, -0.71315846,
        -0.48438067],
       ...,
       [-0.85441295, -0.48639896, -0.42106868, -0.7462239 ,  2.14716028,
        -0.89690689],
       [-0.36222936,  0.29550982, -1.22196069, -0.71337396, -0.26695753,
        -0.68842718],
       [-0.84456284, -0.82220525, -0.57746863, -0.46745965,  0.03400782,
        -0.67287175]])

In [123]:
import numpy as np
from collections import Counter

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        y_pred = [self._predict(x) for x in X]
        return np.array(y_pred)

    def _predict(self, x):
        distances = [self._euclidean_distance(x, x_train) for x_train in self.X_train]
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]
        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]

    def _euclidean_distance(self, x1, x2):
        return np.sqrt(np.sum((x1 - x2) ** 2))

In [124]:
# create an instance of the KNN class with k=5
knn = KNN(k=1)

# fit the model on training data
X_train = x #np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y_train = y #np.array([0, 0, 1, 1])
knn.fit(X_train, y_train)

test = pd.read_csv('./test.csv')
test = test.drop(['Unnamed: 0'], axis=1)
test = StandardScaler().fit_transform(test)

test




array([[ 0.78825138, -0.02035793,  0.10558955,  0.93883438,  0.13823378,
         0.3279307 ],
       [ 0.5950885 ,  0.452083  ,  0.15130988,  0.42268151, -0.06453691,
         1.14425821],
       [-0.70815679, -0.10236298, -1.3257899 , -0.76959756,  0.32838361,
        -0.7575387 ],
       [-1.24123212, -0.6689493 , -1.19919712, -1.04932133, -0.08297531,
        -0.87105322],
       [-0.13589381, -0.45808138, -0.5225561 ,  0.12064799, -0.17380846,
         0.2660796 ],
       [ 0.26580561, -0.29337547,  1.03790462,  0.4919333 , -2.31262845,
         0.29981454],
       [-0.81725709, -1.00516472, -0.62734112, -0.3452841 ,  1.53177232,
        -0.63363388],
       [-0.38470843, -0.68904772, -0.55045937, -0.03041025,  0.00672174,
         0.62535996],
       [-0.33399317,  0.32219139, -0.37153694, -0.58970509,  0.43128537,
         0.41580323],
       [-1.1894062 , -0.40077189, -1.48541463, -1.15254354,  0.96199147,
        -0.79910533],
       [-1.54336405, -0.13462056, -1.56435314, -1.

In [125]:
# predict labels for test data
X_test = test #np.array([[0, 1], [2, 3], [4, 5], [6, 7]])
y_pred = knn.predict(X_test)

# print predicted labels
print(y_pred)  # output: [0 0 1 1]

['Spondylolisthesis' 'Spondylolisthesis' 'Hernia' 'Hernia'
 'Spondylolisthesis' 'Spondylolisthesis' 'Normal' 'Spondylolisthesis'
 'Normal' 'Hernia' 'Hernia' 'Normal' 'Spondylolisthesis' 'Normal'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylolisthesis' 'Normal'
 'Normal' 'Spondylolisthesis' 'Hernia' 'Spondylolisthesis' 'Normal'
 'Hernia' 'Spondylolisthesis' 'Normal' 'Normal' 'Spondylolisthesis'
 'Normal' 'Hernia' 'Spondylolisthesis' 'Normal' 'Spondylolisthesis'
 'Spondylolisthesis' 'Normal' 'Normal' 'Hernia' 'Spondylolisthesis'
 'Hernia' 'Spondylolisthesis' 'Spondylolisthesis' 'Normal' 'Hernia'
 'Normal' 'Spondylolisthesis' 'Spondylolisthesis' 'Hernia'
 'Spondylolisthesis' 'Spondylolisthesis' 'Normal' 'Spondylolisthesis'
 'Normal' 'Spondylolisthesis' 'Spondylolisthesis' 'Normal' 'Hernia'
 'Normal' 'Spondylolisthesis' 'Hernia' 'Hernia' 'Spondylolisthesis'
 'Spondylolisthesis' 'Normal' 'Normal' 'Spondylolisthesis' 'Hernia'
 'Hernia' 'Hernia' 'Normal' 'Hernia' 'Spondylolisthesis'
 'Spo

In [126]:
test

array([[ 0.78825138, -0.02035793,  0.10558955,  0.93883438,  0.13823378,
         0.3279307 ],
       [ 0.5950885 ,  0.452083  ,  0.15130988,  0.42268151, -0.06453691,
         1.14425821],
       [-0.70815679, -0.10236298, -1.3257899 , -0.76959756,  0.32838361,
        -0.7575387 ],
       [-1.24123212, -0.6689493 , -1.19919712, -1.04932133, -0.08297531,
        -0.87105322],
       [-0.13589381, -0.45808138, -0.5225561 ,  0.12064799, -0.17380846,
         0.2660796 ],
       [ 0.26580561, -0.29337547,  1.03790462,  0.4919333 , -2.31262845,
         0.29981454],
       [-0.81725709, -1.00516472, -0.62734112, -0.3452841 ,  1.53177232,
        -0.63363388],
       [-0.38470843, -0.68904772, -0.55045937, -0.03041025,  0.00672174,
         0.62535996],
       [-0.33399317,  0.32219139, -0.37153694, -0.58970509,  0.43128537,
         0.41580323],
       [-1.1894062 , -0.40077189, -1.48541463, -1.15254354,  0.96199147,
        -0.79910533],
       [-1.54336405, -0.13462056, -1.56435314, -1.

In [127]:
count = 217
print("id,class")
for i in y_pred:
    print(str(count) + "," + str(i))
    count += 1

id,class
217,Spondylolisthesis
218,Spondylolisthesis
219,Hernia
220,Hernia
221,Spondylolisthesis
222,Spondylolisthesis
223,Normal
224,Spondylolisthesis
225,Normal
226,Hernia
227,Hernia
228,Normal
229,Spondylolisthesis
230,Normal
231,Spondylolisthesis
232,Spondylolisthesis
233,Spondylolisthesis
234,Normal
235,Normal
236,Spondylolisthesis
237,Hernia
238,Spondylolisthesis
239,Normal
240,Hernia
241,Spondylolisthesis
242,Normal
243,Normal
244,Spondylolisthesis
245,Normal
246,Hernia
247,Spondylolisthesis
248,Normal
249,Spondylolisthesis
250,Spondylolisthesis
251,Normal
252,Normal
253,Hernia
254,Spondylolisthesis
255,Hernia
256,Spondylolisthesis
257,Spondylolisthesis
258,Normal
259,Hernia
260,Normal
261,Spondylolisthesis
262,Spondylolisthesis
263,Hernia
264,Spondylolisthesis
265,Spondylolisthesis
266,Normal
267,Spondylolisthesis
268,Normal
269,Spondylolisthesis
270,Spondylolisthesis
271,Normal
272,Hernia
273,Normal
274,Spondylolisthesis
275,Hernia
276,Hernia
277,Spondylolisthesis
278,Spondylo

In [129]:
# import required libraries
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

# load the iris dataset
#data = load_iris()

# split the data into train and test sets
#X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.3, random_state=42)

# create a Gaussian Naive Bayes classifier
nb = GaussianNB()

# train the classifier using the training data
nb.fit(X_train, y_train)

# make predictions on the test data
y_pred = nb.predict(X_test)

# calculate the accuracy of the classifier
#accuracy = accuracy_score(y_test, y_pred)

# print the accuracy of the classifier
#print("Accuracy:", accuracy)

y_pred


array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])